# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe8fc7aa016a10d01a39346737d841d7134e0d006cd122d6c105b8bf3e9168413969597816e3ea27ca8535b6017941e5eb5a80929e9b974dd36b05c97224b9de

test:
  secret_key_base: af261d0c67e8e1cc512bb3a80a67d70ee45a18339d69db35a18676cb08f1486fc9550941b2dcdbff7aeb2096fe75101fdfb48d9560fd34db58485f5b6b118650

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
